### ISSUE TITLE
Datepicker language changed and json not saved in database

### ISSUE THREAD

**Issue by Juraid** [processwire/processwire#157]
http://prntscr.com/qficmu this is " wire--modules--languagesupport--languagesupport-module"
http://prntscr.com/qficw1 this is datepicker lang changer 

Now lang changer is not working but first one is working. Than date picker successfully saved but

when i change first one like en_US.UTF8 , second photo and scripts are work but datepicker not saved its not send date

**Comment by Mu9tafa-Online** [comment]
@Juraid - post your issue here please: [https://github.com/processwire/processwire-issues](url)

and close this one.

**Comment by BernhardBaumrock** [comment]
@ryancramerdesign can this be closed?
