### ISSUE TITLE
XMPP: Post to PubSub

### ISSUE THREAD

**Issue by sjehuda** [processwire/processwire#286]
Greetings!

In XMPP, using PubSub(1) (XEP-0060), it is possible to store posts as Atom Syndication(2) entries into XMPP(3).

There are several XMPP extensions that apply it, namely XEP-0227 (4) and XEP-0472 (5) which make node `urn:xmpp:microblog:0` as a common choice to manage news for client accounts (e.g. `blog@processwire.com`), yet a component account (e.g. `pubsub.processwire.com`) may use all of its nodes for this purpose.

```
pubsub.processwire.com/
|
|-- updates/
    |-- Sombre
     `-- Varied
|-- releases/
 `-- events/
```
```
pubsub service/
|
|-- node/
    |-- item
     `-- item
|-- node/
 `-- node/
```

A PHP library that can be utilized would be Moxl of Movim.

I have made a script that realizes viewing PubSub node items as Atom XML feeds over HTTP.

1. [XEP-0060: Publish-Subscribe](https://xmpp.org/extensions/xep-0060.html)
2. [RFC 4287: The Atom Syndication Format](https://www.rfc-editor.org/rfc/rfc4287)
3. [Atom Over XMPP](https://datatracker.ietf.org/meeting/66/materials/slides-66-atompub-1.pdf)
4. [XEP-0277: Microblogging over XMPP](https://xmpp.org/extensions/xep-0277.html)
5. [XEP-0472: Pubsub Social Feed](https://xmpp.org/extensions/xep-0472.html)
6. [Moxl](https://github.com/movim/movim/tree/master/src/Moxl)
7. [PubSub Over HTTP](https://codeberg.org/poezio/slixmpp/issues/3526)

**Comment by teppokoivula** [comment]
Please take a look at https://github.com/processwire/processwire/issues/8. Issues should not be opened in this repository, there are separate repositories for issues and feature requests.

That being said, I can’t really see how any of this is related to ProcessWire, so you might want to clarify that as well.

**Comment by sjehuda** [comment]
This is a feature request,. I will open it at @processwire-requests
