### ISSUE TITLE
$session->forceLogin does not update $user variable

### ISSUE THREAD

**Issue by ivangretsky** [processwire/processwire#3]
After using $session->forceLogin($loginUser) the $user variable does not get updated before the page reload. But wire('user') function returns what is needed. It seems a little inconsistent. Is it supposed to be that way, or is it a bug?

**Comment by LostKobrakai** [comment]
Local variables cannot be updated. They are declared like you would do it before the template files are included. They then refer to the object assigned to it. wire() on the other hand is a function, which does lookup the current user object each time it's called. One could create a wrapper object to assign to $user, which does the same, but that's probably not worth the effort for such a small usecase. It's probably best to redirect after forceLogin anyways.

**Comment by ivangretsky** [comment]
Ok, understood. As forceLogin() returns a User object or null It is possible to do something like that:
```
$fl = $session->forceLogin($loginUser);
if ($fl) {
    $user = $fl;
}
```

**Comment by LostKobrakai** [comment]
Sure. There's nothing special about those variables.
