### ISSUE TITLE
PagesExportImport issue with some fieldtypes

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire#312]
Hi @ryancramerdesign - just wanting to make sure this isn't lost forever (I don't think there is any other issue referencing it).

Remember that I am also hacking that chunk of code for the VerifiedURL field.

https://github.com/processwire/processwire/blob/3cc76cc886a49313b4bfb9a1a904bd88d11b7cb7/wire/core/PagesExportImport.php#L973

**Comment by matjazpotocnik** [comment]
@adrianbj, did you want to open an issue here?

**Comment by adrianbj** [comment]
Sorry @matjazpotocnik - not sure how I messed that up. Will close and open in the issues repo
