### ISSUE TITLE
Error: Allowed memory size 

### ISSUE THREAD

**Issue by f-b-g-m** [processwire/processwire#4]
With php 5.5 and lower I'm getting `Error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 123207680 bytes) (line 8 of ` when i try to do 
```
echo '<pre>';
print_r( $page );
echo '</pre>';
```
on a template file.

Works fine with php 5.6 and up.
Also on PW 2.7 it works with php 5.3.

I'm on windows 10 x64 using ampps.

**Comment by yckart** [comment]
I don't think that this is related to ProcessWire. I could imagine that the error is thrown because the size of your `$page`-object has changed. (Maybe, because the base `Page`-class has more public properties, don't know...)

**Comment by ryancramerdesign** [comment]
Thanks for the info on this @yckart . 

@f-b-g-m While you should be able to print_r a $page object, it really may depend on what fields are connected with it. Chances are you are hitting something recursive when doing that, resulting in the out of memory condition. I would probably avoid trying to print_r PW objects and instead output the specific fields that you are looking to pull from them. Though do also check that you don't have at least an 128M memory_limit as @yckart suggested. 

I'm closing out this issues section and moving it to a separate repository for GitHub access control and collaboration purposes. If you want to continue this issue report, please re-open it at: https://github.com/processwire/processwire-issues/issues

Thanks,
Ryan
