### ISSUE TITLE
$page->setAndSave does not work with array as parameter

### ISSUE THREAD

**Issue by ivangretsky** [processwire/processwire#6]
It seems like _setAndSave_ shortcut method does not play well with an array of fields unput.

This code does not work:
```
$page->setAndSave(array(
	'next_action' => 'JustTest',
	'next_action_time' => time() + 12 * 3600,
));
```

This one does:
```
$page->setAndSave(array(
	'next_action' => 'JustTest',
));
```

and this one too (of course):
```
$of = $page->of();
$page->of(false);
$page->next_action = 'JustTest';
$page->save('next_action');
$page->next_action_time = time() + 12 * 3600;
$page->save('next_action_time');
$page->of($of);
```

Or I messed something up)

**Comment by LostKobrakai** [comment]
remove the `;` and it should work

**Comment by ivangretsky** [comment]
The error is in the issue, not in the original code. Sorry about that. The issue is still open.

**Comment by LostKobrakai** [comment]
I'm still not sure about the issue, as the function's implementation (according to git) didn't change for over a year and I've used this many times.

**Comment by jdiderik** [comment]
Have you tried it with setting the value into a temp variable first?
```
$temp = time() + 12 * 3600;
$page->setAndSave(array(
    'next_action' => 'JustTest',
    'next_action_time' => $temp
));
```

**Comment by ivangretsky** [comment]
I did with no luck. Actually I do not get an error but "Connection was reset" (if I translate it correctly) from a browser.

**Comment by ryancramerdesign** [comment]
@ivangretsky I can't seem to duplicate this one. Here's the code I used to test:
~~~~~
$p = $pages->get(1);
$p->setAndSave(array(
        'headline' => 'Test Headline',
        'test_integer' => 3,
));
~~~~~
After executing that code, headline and test_integer were updated to the new values.

When you say that it's not working, can you expand on that–does one value update and not the other, or neither, or you see an error message? Your original code looks good to me, it certainly should work. Probably what needs to be looked at next are the next_action and next_action_time fields. I tried to duplicate your test by using FieldtypeText and FieldtypeInteger fields, is that what you are using as well? What other 3rd party modules are installed?

**Comment by ivangretsky** [comment]
next_action_time is datetime

**Comment by ryancramerdesign** [comment]
I tested again with a datetime field added to the mix, but still working correctly here. 

When you say that it's not working, can you expand on that–does one value update and not the other, or neither, or you see an error message?

What other 3rd party modules are installed?

**Comment by ivangretsky** [comment]
Thank you for your help. I'll test it again and report here. Seems like I messed up somewhere as the issue is not reproduced by all you kind people.

**Comment by ryancramerdesign** [comment]
@ivangretsky I'm going to close this out since I'm moving to the issues repo, but if you find the issue persists please open it at: https://github.com/processwire/processwire-issues/issues

Thanks,
Ryan
