### ISSUE TITLE
Update Link To Reference The New Repository 

### ISSUE THREAD

**Issue by Mustafa-Online** [processwire/processwire#60]

**Comment by adrianbj** [comment]
@gmclelland or @LostKobrakai - can we get this issue closed please?

It was also posted here: https://github.com/processwire/processwire-issues/issues/186 and the issue dealt with.

Thanks.

**Comment by LostKobrakai** [comment]
Only Ryan can close things here.

**Comment by adrianbj** [comment]
Right - sorry about the ping.

@ryancramerdesign - this can be closed when you get a second.
