### ISSUE TITLE
page-publish button does not disappear fully disappear. 

### ISSUE THREAD

**Issue by hagcin** [processwire/processwire#85]
**Bug report:**
When adding the permission "page-publish" ,  and logging in as a user that does not have that permission, the publish button will be removed, but only part way, and a set of links belonging to that button will still show.

**System:**
Clean install with pro drafts, and croppable image 3. ProcessWire 3.0.62

**Browser:** 
Safari

**Use Case:**
Setting up a workflow where users can draft pages, but not publish them. (so that all content can be reviewed first)

Forum Link: https://processwire.com/talk/topic/17082-bug-when-adding-page-publish-permission/#comment-149976

**Comment by adrianbj** [comment]
@hagcin - can you please post this in the dedicated PW issues repo here: https://github.com/processwire/processwire-issues/issues

Thank you!
